# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=63, unique_for_month='pub_date')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=63, unique_for_month='pub_date')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('text', models.TextField()),
                ('members', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='start date')),
                ('status', models.CharField(choices=[('ON', 'ongoing'), ('CPT', 'completed')], default='ON', max_length=5)),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=63, unique_for_month='start_date')),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=63, unique_for_month='pub_date')),
            ],
        ),
    ]
