# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parishioner',
            old_name='communities',
            new_name='community',
        ),
    ]
