# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 09:31
from __future__ import unicode_literals

from datetime import date

from django.db import migrations, models

COMMUNITIES = [
    {
        "name": "St Gabriel",
        "description": "Hausa Catholic Community",
        "leader": "Innocent Tabat",
        "email": "tabati@gmail.com",
        "phone_number": "09049862354",
        "slug": "stgabriel",
    },
    {
        "name": "St Augustine",
        "description": "Tiv Catholic Community",
        "leader":"Winifred Nambativ",
        "email": "winnieN@yahoo.com",
        "phone_number": "08059982354",
        "slug": "staugustine",
    },
    {
        "name": "Ss Peter and Paul",
        "description": "Idoma Catholic Community",
        "leader": "Adama Amanyi",
        "email": "aamanyi@yahoo.com",
        "phone_number": "08029072354",
        "slug": "sspeterandpaul",
    },
]

def add_community_data(apps, schema_editor):
    Community = apps.get_model('people', 'Community')
    for community in COMMUNITIES:
        community_object = Community.objects.create(
            name=community['name'],
            description=community['description'],
            leader=community['leader'],
            email=community['email'],
            phone_number=community['phone_number'],
            slug=community['slug'])

def remove_community_data(apps, schema_editor):
    Community = apps.get_model('people', 'Community')
    for community in COMMUNITIES:
        community_object = Community.objects.get(slug=community['slug'])
        community_object.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_society_data'),
    ]

    operations = [
        migrations.RunPython(
            add_community_data,
            remove_community_data)
    ]
