# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlterBoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41)),
                ('start_date', models.DateField(verbose_name='start date')),
            ],
        ),
        migrations.CreateModel(
            name='Cathecist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41)),
                ('position', models.CharField(help_text='Your position in the parish', max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_posted', models.DateField(verbose_name='date posted')),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41)),
                ('mission', models.TextField(help_text='Diocesan or Missionary')),
                ('position', models.CharField(help_text='Your position in the parish', max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_posted', models.DateField(verbose_name='date posted')),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41)),
                ('mission', models.TextField(help_text='Diocesan or Missionary')),
                ('position', models.CharField(help_text='Your position in the parish', max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_posted', models.DateField(verbose_name='date posted')),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
    ]
