# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alterboy',
            name='slug',
            field=models.SlugField(default='oldschool', max_length=31, unique=True),
        ),
    ]
