# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 09:28
from __future__ import unicode_literals

from datetime import date

from django.db import migrations, models

PRIESTS = [
    {
        "name": "Fr Benjamin Okoro",
        "mission": "Abuja Diocese",
        "position": "Parish Priest",
        "email": "Frben@holyrosary.com",
        "phone_number": "08025562354",
        "date_posted": date(2014, 12, 16),
        "slug": "revbeno",
    },
    {
        "name": "Fr Nicholas Nwalaka",
        "mission": "Abuja Diocese",
        "position":"Associate Priest",
        "email": "nnwalaka@holyrosary.com",
        "phone_number": "09059982354",
        "date_posted": date(2015, 3, 9),
        "slug": "revnickn",
    },
    {
        "name": "Fr Moses Jimbili",
        "mission": "Abuja Diocese",
        "position": "Associate Priest",
        "email": "jmoses@holyrosary.com",
        "phone_number": "09059862354",
        "date_posted": date(2012, 11, 1),
        "slug": "revjimm",
    },
]

def add_priest_data(apps, schema_editor):
    Priest = apps.get_model('churchadmin', 'Priest')
    for priest in PRIESTS:
        priest_object = Priest.objects.create(
            name=priest['name'],
            mission=priest['mission'],
            position=priest['position'],
            email=priest['email'],
            phone_number=priest['phone_number'],
            date_posted=priest['date_posted'],
            slug=priest['slug'])

def remove_priest_data(apps, schema_editor):
    Priest = apps.get_model('churchadmin', 'Priest')
    for priest in PRIESTS:
        priest_object = Priest.objects.get(slug=priest['slug'])
        priest_object.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('churchadmin', '0002_alterboy_slug'),
    ]

    operations = [
        migrations.RunPython(
            add_priest_data,
            remove_priest_data)
    ]
