# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 09:29
from __future__ import unicode_literals

from datetime import date

from django.db import migrations, models

SISTERS = [
    {
        "name": "Mary Ann Polter",
        "mission": "Sacred Heart",
        "position": "Accountant",
        "email": "maryannp@sacredheart.com",
        "phone_number": "08065562354",
        "date_posted": date(2007, 1, 6),
        "slug": "mapolter",
    },
    {
        "name": "Jennifer Garner",
        "mission": "Sacred Heart",
        "position": "Cook",
        "email": "Jenniferg@sacredheart.com",
        "phone_number": "08039062354",
        "date_posted": date(2008, 3, 9),
        "slug": "jgarner",
    },
    {
        "name": "Nkechi Okoronkwo",
        "mission": "Sacred Heart",
        "position": "Rector",
        "email": "nokoronkwo@sacredheart.com",
        "phone_number": "09030062354",
        "date_posted": date(1998, 11, 15),
        "slug": "nokoronkwo",
    },
]

def add_sister_data(apps, schema_editor):
    Sister = apps.get_model('churchadmin', 'Sister')
    for sister in SISTERS:
        sister_object = Sister.objects.create(
            name=sister['name'],
            mission=sister['mission'],
            position=sister['position'],
            email=sister['email'],
            phone_number=sister['phone_number'],
            date_posted=sister['date_posted'],
            slug=sister['slug'])

def remove_sister_data(apps, schema_editor):
    Sister = apps.get_model('churchadmin', 'Sister')
    for sister in SISTERS:
        sister_object = Sister.objects.get(slug=sister['slug'])
        sister_object.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('churchadmin', '0003_priest_data'),
    ]

    operations = [
        migrations.RunPython(
            add_sister_data,
            remove_sister_data)
    ]
