# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 09:29
from __future__ import unicode_literals

from datetime import date

from django.db import migrations, models

CATHECISTS = [
    {
        "name": "Bruce Willis",
        "position": "Assitant Cathecist",
        "email": "Bwillis@gmail.com",
        "phone_number": "08034569871",
        "date_posted": date(2011, 11, 2),
        "slug": "bwillis",
    },
    {
        "name": "Antonio Banderas",
        "position": "Assitant Cathecist",
        "email": "abanderas@yahoo.com",
        "phone_number": "08065569871",
        "date_posted": date(2002, 10, 6),
        "slug": "abanderas",
    },
]

def add_cathecist_data(apps, schema_editor):
    Cathecist = apps.get_model('churchadmin', 'Cathecist')
    for cathecist in CATHECISTS:
        cathecist_object = Cathecist.objects.create(
            name=cathecist['name'],
            position=cathecist['position'],
            email=cathecist['email'],
            phone_number=cathecist['phone_number'],
            date_posted=cathecist['date_posted'],
            slug=cathecist['slug'])

def remove_cathecist_data(apps, schema_editor):
    Cathecist = apps.get_model('churchadmin', 'Cathecist')
    for cathecist in CATHECISTS:
        cathecist_object = Cathecist.objects.get(slug=cathecist['slug'])
        cathecist_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('churchadmin', '0004_sister_data'),
    ]

    operations = [
        migrations.RunPython(
            add_cathecist_data,
            remove_cathecist_data)
    ]
